data:
  sqls:
  - file_name: data/sqls/test-2.sql
    name: test-2
  - file_name: data/sqls/test-5.sql
    name: test-5
description: PoC of Data Console integration with CLI
infra: {}
ml: {}
name: poc
pipelines: {}
