name: Invoke an action on Data Product

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Create branch for changes"
      message:
        description: "Commit and PR message"
      command:
        description: "Cli command"
      options:
        description: "base64 encoded command options"

jobs:
  dispatch:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
      - name: Execute Data Product CLI command
        env:
          DATA_PRODUCT_OPTIONS: ${{ github.event.inputs.options }}
        run: python -m cli.main ${{ github.event.inputs.command }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ github.event.inputs.branch }}
          commit-message: ${{ github.event.inputs.message }}
          title: ${{ github.event.inputs.message }}
          delete-branch: true
